replicaCount: 2

image:
  repository: ""
  digest: ""
  pullPolicy: IfNotPresent

runtime:
  homeSite: ""
  kafkaBrokers: ""
  kafkaTopic: ecommerce.product.events.v1
  kafkaTLSSecretName: product-kafka-tls
  otlpEndpoint: ""
  oidcIssuer: ""
  oidcAudience: admin
  secretName: product-runtime

resources:
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 64Mi
  limits:
    memory: 256Mi
    ephemeral-storage: 128Mi

autoscaling:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

migration:
  activeDeadlineSeconds: 300
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
      ephemeral-storage: 16Mi
    limits:
      memory: 64Mi
      ephemeral-storage: 32Mi
