---
- name: Configure MGMT Rocky Linux baseline
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: rocky_baseline

- name: Bootstrap first RKE2 control plane
  hosts: cp-01
  become: true
  gather_facts: false

  roles:
    - role: rke2_server

- name: Join remaining RKE2 control planes
  hosts:
    - cp-02
    - cp-03
  become: true
  gather_facts: false

  roles:
    - role: rke2_server

- name: Join RKE2 workers
  hosts: rke2_agents
  become: true
  gather_facts: false

  roles:
    - role: rke2_agent
