apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: ecommerce-global-gates
spec:
  params:
    - name: runner-image
      type: string
  workspaces:
    - name: source
  steps:
    - name: global-gates
      image: $(params.runner-image)
      workingDir: $(workspaces.source.path)
      command: [make]
      args: [ci-global]
