// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CommandJournal struct {
	JournalKey    string
	Fingerprint   string
	ResultKind    string
	ResultPayload []byte
	CreatedAt     pgtype.Timestamptz
}

type Product struct {
	ID                     string
	Name                   string
	Description            string
	Brand                  string
	ManufacturerPartNumber string
	Status                 string
	Attributes             []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Version                int64
}

type Sku struct {
	ID           string
	ProductID    string
	Code         string
	Gtin         string
	Status       string
	OptionValues []byte
	Attributes   []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Version      int64
}
