// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSKU(ctx context.Context, arg CreateSKUParams) (Sku, error)
	GetCommand(ctx context.Context, journalKey string) (CommandJournal, error)
	GetProduct(ctx context.Context, id string) (Product, error)
	GetSKU(ctx context.Context, arg GetSKUParams) (Sku, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByStatus(ctx context.Context, arg ListProductsByStatusParams) ([]Product, error)
	ListSKUs(ctx context.Context, arg ListSKUsParams) ([]Sku, error)
	SaveCommand(ctx context.Context, arg SaveCommandParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateSKU(ctx context.Context, arg UpdateSKUParams) (Sku, error)
}

var _ Querier = (*Queries)(nil)
