// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    id, name, description, brand, manufacturer_part_number,
    status, attributes, created_at, updated_at, version
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
RETURNING id, name, description, brand, manufacturer_part_number, status, attributes, created_at, updated_at, version
`

type CreateProductParams struct {
	ID                     string
	Name                   string
	Description            string
	Brand                  string
	ManufacturerPartNumber string
	Status                 string
	Attributes             []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Version                int64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.ManufacturerPartNumber,
		arg.Status,
		arg.Attributes,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Version,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.ManufacturerPartNumber,
		&i.Status,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createSKU = `-- name: CreateSKU :one
INSERT INTO skus (
    id, product_id, code, gtin, status, option_values, attributes,
    created_at, updated_at, version
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
RETURNING id, product_id, code, gtin, status, option_values, attributes, created_at, updated_at, version
`

type CreateSKUParams struct {
	ID           string
	ProductID    string
	Code         string
	Gtin         string
	Status       string
	OptionValues []byte
	Attributes   []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Version      int64
}

func (q *Queries) CreateSKU(ctx context.Context, arg CreateSKUParams) (Sku, error) {
	row := q.db.QueryRow(ctx, createSKU,
		arg.ID,
		arg.ProductID,
		arg.Code,
		arg.Gtin,
		arg.Status,
		arg.OptionValues,
		arg.Attributes,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Version,
	)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Gtin,
		&i.Status,
		&i.OptionValues,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCommand = `-- name: GetCommand :one
SELECT journal_key, fingerprint, result_kind, result_payload, created_at
FROM command_journal
WHERE journal_key = $1
`

func (q *Queries) GetCommand(ctx context.Context, journalKey string) (CommandJournal, error) {
	row := q.db.QueryRow(ctx, getCommand, journalKey)
	var i CommandJournal
	err := row.Scan(
		&i.JournalKey,
		&i.Fingerprint,
		&i.ResultKind,
		&i.ResultPayload,
		&i.CreatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, brand, manufacturer_part_number, status, attributes, created_at, updated_at, version FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.ManufacturerPartNumber,
		&i.Status,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getSKU = `-- name: GetSKU :one
SELECT id, product_id, code, gtin, status, option_values, attributes, created_at, updated_at, version
FROM skus
WHERE product_id = $1
  AND id = $2
`

type GetSKUParams struct {
	ProductID string
	ID        string
}

func (q *Queries) GetSKU(ctx context.Context, arg GetSKUParams) (Sku, error) {
	row := q.db.QueryRow(ctx, getSKU, arg.ProductID, arg.ID)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Gtin,
		&i.Status,
		&i.OptionValues,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, brand, manufacturer_part_number, status, attributes, created_at, updated_at, version
FROM products
ORDER BY id
LIMIT $2::integer
OFFSET $1::integer
`

type ListProductsParams struct {
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.ManufacturerPartNumber,
			&i.Status,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByStatus = `-- name: ListProductsByStatus :many
SELECT id, name, description, brand, manufacturer_part_number, status, attributes, created_at, updated_at, version
FROM products
WHERE status = $1
ORDER BY id
LIMIT $3::integer
OFFSET $2::integer
`

type ListProductsByStatusParams struct {
	Status      string
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListProductsByStatus(ctx context.Context, arg ListProductsByStatusParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByStatus, arg.Status, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.ManufacturerPartNumber,
			&i.Status,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSKUs = `-- name: ListSKUs :many
SELECT id, product_id, code, gtin, status, option_values, attributes, created_at, updated_at, version
FROM skus
WHERE product_id = $1
ORDER BY id
LIMIT $3::integer
OFFSET $2::integer
`

type ListSKUsParams struct {
	ProductID   string
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListSKUs(ctx context.Context, arg ListSKUsParams) ([]Sku, error) {
	rows, err := q.db.Query(ctx, listSKUs, arg.ProductID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sku{}
	for rows.Next() {
		var i Sku
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Code,
			&i.Gtin,
			&i.Status,
			&i.OptionValues,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCommand = `-- name: SaveCommand :exec
INSERT INTO command_journal (journal_key, fingerprint, result_kind, result_payload)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type SaveCommandParams struct {
	JournalKey    string
	Fingerprint   string
	ResultKind    string
	ResultPayload []byte
}

func (q *Queries) SaveCommand(ctx context.Context, arg SaveCommandParams) error {
	_, err := q.db.Exec(ctx, saveCommand,
		arg.JournalKey,
		arg.Fingerprint,
		arg.ResultKind,
		arg.ResultPayload,
	)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $1,
    description = $2,
    brand = $3,
    manufacturer_part_number = $4,
    status = $5,
    attributes = $6,
    updated_at = $7,
    version = $8
WHERE id = $9
  AND version = $10
RETURNING id, name, description, brand, manufacturer_part_number, status, attributes, created_at, updated_at, version
`

type UpdateProductParams struct {
	Name                   string
	Description            string
	Brand                  string
	ManufacturerPartNumber string
	Status                 string
	Attributes             []byte
	UpdatedAt              pgtype.Timestamptz
	Version                int64
	ID                     string
	ExpectedVersion        int64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.ManufacturerPartNumber,
		arg.Status,
		arg.Attributes,
		arg.UpdatedAt,
		arg.Version,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.ManufacturerPartNumber,
		&i.Status,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateSKU = `-- name: UpdateSKU :one
UPDATE skus
SET code = $1,
    gtin = $2,
    status = $3,
    option_values = $4,
    attributes = $5,
    updated_at = $6,
    version = $7
WHERE product_id = $8
  AND id = $9
  AND version = $10
RETURNING id, product_id, code, gtin, status, option_values, attributes, created_at, updated_at, version
`

type UpdateSKUParams struct {
	Code            string
	Gtin            string
	Status          string
	OptionValues    []byte
	Attributes      []byte
	UpdatedAt       pgtype.Timestamptz
	Version         int64
	ProductID       string
	ID              string
	ExpectedVersion int64
}

func (q *Queries) UpdateSKU(ctx context.Context, arg UpdateSKUParams) (Sku, error) {
	row := q.db.QueryRow(ctx, updateSKU,
		arg.Code,
		arg.Gtin,
		arg.Status,
		arg.OptionValues,
		arg.Attributes,
		arg.UpdatedAt,
		arg.Version,
		arg.ProductID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Gtin,
		&i.Status,
		&i.OptionValues,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
