// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkReadiness = `-- name: CheckReadiness :one
SELECT (
    to_regclass('public.products') IS NOT NULL
    AND to_regclass('public.skus') IS NOT NULL
    AND to_regclass('public.command_journal') IS NOT NULL
    AND to_regclass('public.outbox_events') IS NOT NULL
    AND to_regclass('public.outbox_dead_letters') IS NOT NULL
)::boolean AS ready
`

func (q *Queries) CheckReadiness(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, checkReadiness)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
WITH candidates AS (
    SELECT candidate.event_id
    FROM outbox_events AS candidate
    WHERE candidate.published_at IS NULL
      AND candidate.available_at <= $2
      AND candidate.attempt_count <= $3
      AND NOT EXISTS (
          SELECT 1
          FROM outbox_events AS predecessor
          WHERE predecessor.aggregate_type = candidate.aggregate_type
            AND predecessor.aggregate_id = candidate.aggregate_id
            AND predecessor.published_at IS NULL
            AND predecessor.aggregate_version < candidate.aggregate_version
      )
    ORDER BY candidate.occurred_at_utc, candidate.event_id
    FOR UPDATE SKIP LOCKED
    LIMIT $4
)
UPDATE outbox_events AS event
SET attempt_count = event.attempt_count + 1,
    available_at = $1
FROM candidates
WHERE event.event_id = candidates.event_id
RETURNING event.event_id, event.event_type, event.schema_version, event.aggregate_id,
          event.payload, event.attempt_count
`

type ClaimOutboxEventsParams struct {
	PLeaseUntil      pgtype.Timestamptz
	PAvailableBefore pgtype.Timestamptz
	PMaxAttempts     int32
	PLimitCount      int32
}

type ClaimOutboxEventsRow struct {
	EventID       string
	EventType     string
	SchemaVersion int32
	AggregateID   string
	Payload       []byte
	AttemptCount  int32
}

func (q *Queries) ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]ClaimOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents,
		arg.PLeaseUntil,
		arg.PAvailableBefore,
		arg.PMaxAttempts,
		arg.PLimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimOutboxEventsRow{}
	for rows.Next() {
		var i ClaimOutboxEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.EventType,
			&i.SchemaVersion,
			&i.AggregateID,
			&i.Payload,
			&i.AttemptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    id, name, description, brand, manufacturer_part_number,
    status, attributes, created_at, updated_at, version
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
RETURNING id, name, description, brand, manufacturer_part_number, status, attributes, created_at, updated_at, version
`

type CreateProductParams struct {
	ID                     string
	Name                   string
	Description            string
	Brand                  string
	ManufacturerPartNumber string
	Status                 string
	Attributes             []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Version                int64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.ManufacturerPartNumber,
		arg.Status,
		arg.Attributes,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Version,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.ManufacturerPartNumber,
		&i.Status,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createSKU = `-- name: CreateSKU :one
INSERT INTO skus (
    id, product_id, code, gtin, status, option_values, attributes,
    created_at, updated_at, version
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
RETURNING id, product_id, code, gtin, status, option_values, attributes, created_at, updated_at, version
`

type CreateSKUParams struct {
	ID           string
	ProductID    string
	Code         string
	Gtin         string
	Status       string
	OptionValues []byte
	Attributes   []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Version      int64
}

func (q *Queries) CreateSKU(ctx context.Context, arg CreateSKUParams) (Sku, error) {
	row := q.db.QueryRow(ctx, createSKU,
		arg.ID,
		arg.ProductID,
		arg.Code,
		arg.Gtin,
		arg.Status,
		arg.OptionValues,
		arg.Attributes,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Version,
	)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Gtin,
		&i.Status,
		&i.OptionValues,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCommand = `-- name: GetCommand :one
SELECT journal_key, fingerprint, result_kind, result_payload, created_at
FROM command_journal
WHERE journal_key = $1
`

func (q *Queries) GetCommand(ctx context.Context, journalKey string) (CommandJournal, error) {
	row := q.db.QueryRow(ctx, getCommand, journalKey)
	var i CommandJournal
	err := row.Scan(
		&i.JournalKey,
		&i.Fingerprint,
		&i.ResultKind,
		&i.ResultPayload,
		&i.CreatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, brand, manufacturer_part_number, status, attributes, created_at, updated_at, version FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.ManufacturerPartNumber,
		&i.Status,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getSKU = `-- name: GetSKU :one
SELECT id, product_id, code, gtin, status, option_values, attributes, created_at, updated_at, version
FROM skus
WHERE product_id = $1
  AND id = $2
`

type GetSKUParams struct {
	ProductID string
	ID        string
}

func (q *Queries) GetSKU(ctx context.Context, arg GetSKUParams) (Sku, error) {
	row := q.db.QueryRow(ctx, getSKU, arg.ProductID, arg.ID)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Gtin,
		&i.Status,
		&i.OptionValues,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (
    event_id, event_type, schema_version, occurred_at_utc, producer,
    aggregate_type, aggregate_id, aggregate_version,
    correlation_id, causation_id, home_site, payload
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12
)
`

type InsertOutboxEventParams struct {
	EventID          string
	EventType        string
	SchemaVersion    int32
	OccurredAtUtc    pgtype.Timestamptz
	Producer         string
	AggregateType    string
	AggregateID      string
	AggregateVersion int64
	CorrelationID    string
	CausationID      string
	HomeSite         string
	Payload          []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.SchemaVersion,
		arg.OccurredAtUtc,
		arg.Producer,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.CorrelationID,
		arg.CausationID,
		arg.HomeSite,
		arg.Payload,
	)
	return err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, brand, manufacturer_part_number, status, attributes, created_at, updated_at, version
FROM products
ORDER BY id
LIMIT $2::integer
OFFSET $1::integer
`

type ListProductsParams struct {
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.ManufacturerPartNumber,
			&i.Status,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByStatus = `-- name: ListProductsByStatus :many
SELECT id, name, description, brand, manufacturer_part_number, status, attributes, created_at, updated_at, version
FROM products
WHERE status = $1
ORDER BY id
LIMIT $3::integer
OFFSET $2::integer
`

type ListProductsByStatusParams struct {
	Status      string
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListProductsByStatus(ctx context.Context, arg ListProductsByStatusParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByStatus, arg.Status, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.ManufacturerPartNumber,
			&i.Status,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSKUs = `-- name: ListSKUs :many
SELECT id, product_id, code, gtin, status, option_values, attributes, created_at, updated_at, version
FROM skus
WHERE product_id = $1
ORDER BY id
LIMIT $3::integer
OFFSET $2::integer
`

type ListSKUsParams struct {
	ProductID   string
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListSKUs(ctx context.Context, arg ListSKUsParams) ([]Sku, error) {
	rows, err := q.db.Query(ctx, listSKUs, arg.ProductID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sku{}
	for rows.Next() {
		var i Sku
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Code,
			&i.Gtin,
			&i.Status,
			&i.OptionValues,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox_events
SET published_at = $1, last_error = ''
WHERE event_id = $2 AND published_at IS NULL
`

type MarkOutboxPublishedParams struct {
	PPublishedAt pgtype.Timestamptz
	PEventID     string
}

func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, arg.PPublishedAt, arg.PEventID)
	return err
}

const moveOutboxEventToDeadLetter = `-- name: MoveOutboxEventToDeadLetter :exec
WITH moved AS (
    DELETE FROM outbox_events AS event
    WHERE event.event_id = $2 AND event.published_at IS NULL
    RETURNING event.event_id, event.event_type, event.schema_version, event.occurred_at_utc, event.producer,
              event.aggregate_type, event.aggregate_id, event.aggregate_version,
              event.correlation_id, event.causation_id,
              event.home_site, event.payload, event.attempt_count
)
INSERT INTO outbox_dead_letters (
    event_id, event_type, schema_version, occurred_at_utc, producer,
    aggregate_type, aggregate_id, aggregate_version, correlation_id, causation_id,
    home_site, payload, attempt_count, last_error
)
SELECT event_id, event_type, schema_version, occurred_at_utc, producer,
       aggregate_type, aggregate_id, aggregate_version, correlation_id, causation_id,
       home_site, payload, attempt_count, $1
FROM moved
`

type MoveOutboxEventToDeadLetterParams struct {
	PLastError string
	PEventID   string
}

func (q *Queries) MoveOutboxEventToDeadLetter(ctx context.Context, arg MoveOutboxEventToDeadLetterParams) error {
	_, err := q.db.Exec(ctx, moveOutboxEventToDeadLetter, arg.PLastError, arg.PEventID)
	return err
}

const rescheduleOutboxEvent = `-- name: RescheduleOutboxEvent :exec
UPDATE outbox_events
SET available_at = $1, last_error = $2
WHERE event_id = $3 AND published_at IS NULL
`

type RescheduleOutboxEventParams struct {
	PAvailableAt pgtype.Timestamptz
	PLastError   string
	PEventID     string
}

func (q *Queries) RescheduleOutboxEvent(ctx context.Context, arg RescheduleOutboxEventParams) error {
	_, err := q.db.Exec(ctx, rescheduleOutboxEvent, arg.PAvailableAt, arg.PLastError, arg.PEventID)
	return err
}

const saveCommand = `-- name: SaveCommand :exec
INSERT INTO command_journal (journal_key, fingerprint, result_kind, result_payload)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type SaveCommandParams struct {
	JournalKey    string
	Fingerprint   string
	ResultKind    string
	ResultPayload []byte
}

func (q *Queries) SaveCommand(ctx context.Context, arg SaveCommandParams) error {
	_, err := q.db.Exec(ctx, saveCommand,
		arg.JournalKey,
		arg.Fingerprint,
		arg.ResultKind,
		arg.ResultPayload,
	)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $1,
    description = $2,
    brand = $3,
    manufacturer_part_number = $4,
    status = $5,
    attributes = $6,
    updated_at = $7,
    version = $8
WHERE id = $9
  AND version = $10
RETURNING id, name, description, brand, manufacturer_part_number, status, attributes, created_at, updated_at, version
`

type UpdateProductParams struct {
	Name                   string
	Description            string
	Brand                  string
	ManufacturerPartNumber string
	Status                 string
	Attributes             []byte
	UpdatedAt              pgtype.Timestamptz
	Version                int64
	ID                     string
	ExpectedVersion        int64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.ManufacturerPartNumber,
		arg.Status,
		arg.Attributes,
		arg.UpdatedAt,
		arg.Version,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.ManufacturerPartNumber,
		&i.Status,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateSKU = `-- name: UpdateSKU :one
UPDATE skus
SET code = $1,
    gtin = $2,
    status = $3,
    option_values = $4,
    attributes = $5,
    updated_at = $6,
    version = $7
WHERE product_id = $8
  AND id = $9
  AND version = $10
RETURNING id, product_id, code, gtin, status, option_values, attributes, created_at, updated_at, version
`

type UpdateSKUParams struct {
	Code            string
	Gtin            string
	Status          string
	OptionValues    []byte
	Attributes      []byte
	UpdatedAt       pgtype.Timestamptz
	Version         int64
	ProductID       string
	ID              string
	ExpectedVersion int64
}

func (q *Queries) UpdateSKU(ctx context.Context, arg UpdateSKUParams) (Sku, error) {
	row := q.db.QueryRow(ctx, updateSKU,
		arg.Code,
		arg.Gtin,
		arg.Status,
		arg.OptionValues,
		arg.Attributes,
		arg.UpdatedAt,
		arg.Version,
		arg.ProductID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Gtin,
		&i.Status,
		&i.OptionValues,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
