---
local_gitea_version: "1.24.6"
local_gitea_binary: ""
local_gitea_binary_sha256: ""
local_gitea_rpm_root: ""
local_gitea_rpm_keys: ""
local_gitea_admin_username: "qualification-admin"
local_gitea_admin_email: "qualification-admin@localhost.invalid"
local_gitea_admin_password: ""
local_gitea_secret_key: ""
local_gitea_internal_token: ""
local_gitea_lfs_jwt_secret: ""
local_gitea_repository_name: ""
local_gitea_git_public_key: ""
