apiVersion: v1
kind: ServiceAccount
metadata: {name: tekton-eventlistener}
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: tekton-pipeline}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: tekton-eventlistener}
rules:
  - apiGroups: [triggers.tekton.dev]
    resources: [eventlisteners, triggerbindings, triggertemplates]
    verbs: [get, list, watch]
  - apiGroups: [tekton.dev]
    resources: [pipelineruns]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: tekton-eventlistener}
subjects: [{kind: ServiceAccount, name: tekton-eventlistener}]
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: tekton-eventlistener}
