apiVersion: ecommerce.dev/v1alpha1
kind: SecretContract
metadata:
  name: ghcr-pull
  namespace: tekton-ci
spec:
  activationStatus: NOT_PROVEN
  kubernetesType: kubernetes.io/dockerconfigjson
  registry: https://ghcr.io
  permission: packages:read
  allowedConsumers: [tekton-image-read]
  rotationRequired: true
  repositoryValuesForbidden: true
