#!/bin/sh
set -eu

# Human-gated initializer for the single external project secret file.
# This script never prints the generated password or private age identity.

fail() {
  printf '%s\n' "project secret initialization failed: $*" >&2
  exit 1
}

usage() {
  printf '%s\n' "usage: $0 [--force]"
}

force=0
case ${1:-} in
  '') ;;
  --force) force=1 ;;
  -h|--help) usage; exit 0 ;;
  *) usage >&2; exit 2 ;;
esac
[ "$#" -le 1 ] || { usage >&2; exit 2; }

command -v python3 >/dev/null 2>&1 || fail "python3 is required"
command -v age-keygen >/dev/null 2>&1 || fail "age-keygen is required"
command -v mktemp >/dev/null 2>&1 || fail "mktemp is required"

real_home=$(python3 -c 'import os, pwd; print(pwd.getpwuid(os.geteuid()).pw_dir)') ||
  fail "cannot determine the current account home"
case $real_home in
  /mnt/c|/mnt/c/*|/tmp|/tmp/*|*OneDrive*) fail "the account home is in a forbidden location" ;;
  /*) ;;
  *) fail "the account home is not absolute" ;;
esac

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
repository=$(CDPATH='' cd -- "$script_dir/.." && pwd -P)
project_dir=$real_home/.config/ecommerce-1
env_file=$project_dir/.env
case $project_dir in
  "$repository"|"$repository"/*) fail "the canonical project environment is inside the repository" ;;
esac

[ ! -L "$real_home/.config" ] || fail "$real_home/.config must not be a symlink"
[ ! -L "$project_dir" ] || fail "$project_dir must not be a symlink"
mkdir -p -- "$project_dir"
chmod 0700 "$project_dir"
python3 - "$project_dir" <<'PY' || exit 1
import os
import stat
import sys

path = sys.argv[1]
status = os.lstat(path)
mode = stat.S_IMODE(status.st_mode)
if not stat.S_ISDIR(status.st_mode) or status.st_uid != os.geteuid() or mode != 0o700:
    print("project secret initialization failed: canonical directory is not owned mode 0700", file=sys.stderr)
    raise SystemExit(1)
PY

if [ -L "$env_file" ]; then
  fail "$env_file must not be a symlink"
fi
if [ -e "$env_file" ]; then
  [ -f "$env_file" ] || fail "$env_file must be a regular file"
  [ "$force" -eq 1 ] || fail "$env_file already exists; use --force for an explicit replacement"
  python3 - "$env_file" <<'PY' || exit 1
import os
import stat
import sys

status = os.lstat(sys.argv[1])
if status.st_uid != os.geteuid() or stat.S_IMODE(status.st_mode) & ~0o600:
    print("project secret initialization failed: existing file owner or permissions are unsafe", file=sys.stderr)
    raise SystemExit(1)
PY
fi

umask 077
temporary=
password=
age_output=
identity=
recipient=
cleanup() {
  if [ -n "$temporary" ] && [ -f "$temporary" ]; then
    rm -f -- "$temporary"
  fi
  unset password age_output identity recipient
}
trap cleanup 0 1 2 15

password=$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))') ||
  fail "PostgreSQL password generation failed"
[ "${#password}" -ge 32 ] || fail "PostgreSQL password generation returned an invalid result"

age_output=$(age-keygen 2>/dev/null) || fail "age identity generation failed"
identity=$(printf '%s\n' "$age_output" | awk '
  /^AGE-SECRET-KEY-1/ { count += 1; identity = $0 }
  END { if (count != 1) exit 1; printf "%s", identity }
') || fail "age identity generation returned an invalid result"
unset age_output
recipient=$(printf '%s\n' "$identity" | age-keygen -y 2>/dev/null) ||
  fail "age recipient derivation failed"
case $recipient in
  age1*) ;;
  *) fail "age recipient derivation returned an invalid result" ;;
esac

temporary=$(mktemp "$project_dir/.env.tmp.XXXXXX") || fail "cannot create the protected temporary file"
chmod 0600 "$temporary"
{
  printf '%s\n' '# Generated by scripts/init-project-secrets.sh. Do not copy into the repository.'
  printf 'TERRAFORM_STATE_POSTGRESQL_PASSWORD=%s\n' "$password"
  printf 'TERRAFORM_STATE_BACKUP_AGE_IDENTITY=%s\n' "$identity"
  printf 'TERRAFORM_STATE_BACKUP_AGE_RECIPIENT=%s\n' "$recipient"
} >"$temporary"

if [ "$force" -eq 1 ]; then
  python3 - "$temporary" "$env_file" <<'PY'
import os
import sys

os.replace(sys.argv[1], sys.argv[2])
PY
else
  python3 - "$temporary" "$env_file" <<'PY'
import os
import sys

os.link(sys.argv[1], sys.argv[2])
os.unlink(sys.argv[1])
PY
fi
temporary=
chmod 0600 "$env_file"
unset password identity

python3 "$script_dir/run-with-project-env.py" --env-file "$env_file" --check-only >/dev/null
printf '%s\n' "Project secret file: $env_file"
printf '%s\n' "Directory mode: 0700"
printf '%s\n' "File mode: 0600"
printf '%s\n' "Public age recipient: $recipient"
printf '%s\n' "Project secret initialization: PASS"
