apiVersion: ecommerce.dev/v1alpha1
kind: SecretContract
metadata:
  name: signing-secrets
  namespace: tekton-chains
spec:
  activationStatus: NOT_PROVEN
  kubernetesType: Opaque
  provisionedBy: external-secret-management-process
  allowedConsumers:
    - system:serviceaccount:tekton-chains:tekton-chains-controller
  alternatives:
    - name: x509
      requiredKeys: [x509.pem]
    - name: cosign
      requiredKeys: [cosign.key, cosign.password]
    - name: kms
      requiredConfiguration: [signers.kms.kmsref]
  repositoryValuesForbidden: true
  rotationRequired: true
