require "json"

runtime = JSON.parse(File.read(File.join(__dir__, "runtime.json")))
name = runtime.fetch("name")
raise "invalid owned local-service VM name" unless name.match?(/\Aecommerce-local-(gitea|harbor)-[0-9a-f]{12}\z/)
port = Integer(runtime.fetch("ssh_host_port"))
raise "invalid SSH host port" unless (1024..65_535).cover?(port)
seed_port = Integer(runtime.fetch("seed_port"))
raise "invalid seed port" unless (1024..65_535).cover?(seed_port)

Vagrant.require_version "= #{runtime.fetch("vagrant_version")}"
Vagrant.configure("2") do |config|
  config.vm.box = runtime.fetch("box_name")
  config.vm.box_check_update = false
  config.vm.communicator = "none"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "forwarded_port", guest: 22, host: port, host_ip: "127.0.0.1", id: "ssh", auto_correct: false

  config.vm.provider "virtualbox" do |vm|
    vm.name = name
    vm.memory = Integer(runtime.fetch("memory_mib"))
    vm.cpus = Integer(runtime.fetch("cpus"))
    vm.linked_clone = false
    vm.check_guest_additions = false
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nic1", "nat"]
    vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vm.customize ["modifyvm", :id, "--nat-localhostreachable1", "on"]
    vm.customize [
      "setextradata",
      :id,
      "VBoxInternal/Devices/pcbios/0/Config/DmiSystemSerial",
      "ds=nocloud-net;s=http://10.0.2.2:#{seed_port}/",
    ]
    (2..8).each { |number| vm.customize ["modifyvm", :id, "--nic#{number}", "none"] }
    vm.customize ["modifyvm", :id, "--clipboard-mode", "disabled", "--draganddrop", "disabled", "--vrde", "off"]
  end
end
